- name: Deploy a web applicatin
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: Install all required dependencies
      apt: 
        pkg:
          - python
          - python-setuptools
          - python-dev
          - build-essential        
        state: present
        autoclean: yes
    
    
    - name: Install Mysql database
      apt: 
        pkg:
          - mysql-server
          - mysql-client
          - python-mysqldb
        state: present
        autoclean: yes   

    
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
    
 

    - name: Create Application Database
      mysql_db:
        name: employee_db state=present  

    - name: Create database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install pip
      apt:
        pkg:
          - python-pip
        state: present  

    - name: Install flask
      pip:
        name:
          - flask
          - flask-mysql
        state: present    
    
    - name: Copy source Code
      copy: src=app.py dest=/opt/app.py
      
    - name: Start Web Server
      shell:   FLASK_APP=app.py flask run --host=0.0.0.0