- name: Deploy a web applicatin
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: Install all required dependencies
      apt: 
        pkg:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - python3-pip
          - python3-gunicorn
          - gunicorn3
        
        state: present
        autoclean: yes
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml    
    
    
