---

    
    - name: Install pip
      apt:
        pkg:
          - python-pip
        state: present

    - name: Update setuptools
      pip:
        name: setuptools
        extra_args: --upgrade      

    - name: Install flask
      pip: 
        name: flask
        state: present

    - name: Install markupsafe
      pip: 
        name: markupsafe
        state: present

    - name: Install Flask MySQL
      pip: 
        name: flask-mysql
        state: present              
    

    - name: Copy source Code
      copy: src=app.py dest=/opt/app.py
      
    - name: Start Web Server
      shell:   FLASK_APP=app.py flask run --host=0.0.0.0